baseURL = 'https://chesgreen.github.io/'
languageCode = 'en-us'
title = 'chesgreen.github.io'
theme = "PaperMod"
publishDir = "docs"

[[menu.main]]
name = "About"
url = "about/"
weight = 5

[[menu.main]]
name = "Archive"
url = "archive"
weight = 10

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
env = "production"
description = "My personal site - https://github.com/chesgreen/chesgreen-hugo"
author = "Chester Green"
defaultTheme = "auto"
ShowShareButtons = false
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowToc = true

[homeInfoParams]

  [params.homeInfoParams]
  Title = "Cloud, Code and Automation"
  Content = """
Documenting my learning journey.
"""

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/chesgreen"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/chester-a-green"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:chesgreen@gmail.com"